### ISSUE TITLE
JavaScript - page three-filtering functionality

### ISSUE THREAD

**Issue by RyanPersaud03** [RyanPersaud03/geekymoviewizard#12]
## User Story
once user has filled out questions about movie on page two 
I want to be able to re-filter my options based on genre , location and overall Rating with a drop down menu 

## Acceptance criteria
- [x] able to filter by genre
- [ ] able to filter by location
- [ ] able to filter by overall ratings
- [x] movies with filters are displayed on page

**Comment by afzama** [comment]
future functionality will include location and ratings
