### ISSUE TITLE
CSS Frame-Work Materialize

### ISSUE THREAD

**Issue by RyanPersaud03** [RyanPersaud03/geekymoviewizard#2]
## User Story
As a movie fanatic I want to see a movie webpage in familiar styling to manatee tank presentation colors

## Acceptance Criteria 

ALL PAGES
it is done when webpage has a color theme of 
- [x] heading blue
- [x] background light green
- [x] navigation buttons & about me red
- [x] text can be black 

PAGE 2
- [x] All questions appear on page in a border
- [x] All headings and instructions to be styled same as page 1

**Comment by afzama** [comment]
good work @mk10100
